version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Dependencies
          command: |
            akp add --no-cache \
               aws-cli=1.22.81-r0
      - run:
          name: Build Application Docker Image
          command: docker build -t app .
      - run:
          name: Push Image to ECR
          command: |
            region=eu-west-2
            # TODO: How to work for prod vs staging?
            # TODO: Only push on master
            account_id=713170488151
            ecr_endpoint="$account_id.dkr.ecr.$region.amazonaws.com"
            aws ecr get-login-password --region $region | docker login --username AWS --password-stdin $ecr_endpoint
            docker tag app "$ecr_endpoint:${CIRCLE_SHA1}"
            docker push "$ecr_endpoint:${CIRCLE_SHA1}"

# Orchestrate our job run sequence
workflows:
  build:
    jobs:
      - build
