version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Dependencies
          command: |
            akp add --no-cache \
               aws-cli=1.22.81-r0
      - run:
          name: Build Application Docker Image
          command: docker build -t app .

# Orchestrate our job run sequence
workflows:
  build:
    jobs:
      - build
